{% set name = "fdasrsf" %}
{% set version = "2.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fdasrsf-{{ version }}.tar.gz
  sha256: b9fdc2c8f2eda5136de131fcef2c65970856ac17c0eb4b909d3f15ee7d3a55b9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cffi >=1.0.0
    - cython >=0.29.17
    - numpy >=1.18
    - pip
    - python
  run:
    - cffi >=1.0.0
    - cython >=0.29.17
    - joblib >=0.16.0
    - matplotlib-base
    - numba >=0.51.2
    - patsy
    - pyparsing
    - python
    - scipy >=1.5
    - six
    - tqdm
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fdasrsf
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://research.tetonedge.net
  summary: functional data analysis using the square root slope framework
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: |
    A python package for functional data analysis using the square root 
    slope framework and curves using the square root velocity framework 
    which performs pair-wise and group-wise alignment as well as modeling 
    using functional component analysis and regression.
  doc_url: https://fdasrsf-python.readthedocs.io/
  dev_url: https://github.com/jdtuck/fdasrsf_python

extra:
  recipe-maintainers:
    - jdtuck
