{% set name = "fdasrsf" %}
{% set version = "2.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fdasrsf-{{ version }}.tar.gz
  sha256: 189d3a124511fc2fb903810ad98a8e6db5354d6a3c8bb7266d6f5254a20c38c9

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                               # [build_platform != target_platform]
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
    - numpy {{ numpy }}                    # [build_platform != target_platform]
    - cython                               # [build_platform != target_platform]
    - cffi >=1.0.0                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy {{ numpy }}
    - cffi >=1.0.0
    - cython >=0.29.17
    - pip
  run:
    - python
    - setuptools
    - numpy {{ numpy }}
    - cffi >=1.0.0
    - cython >=0.29.17
    - joblib >=0.16.0
    - matplotlib-base
    - numba >=0.51.2
    - patsy
    - pyparsing
    - scipy
    - six
    - tqdm

test:
  imports:
    - fdasrsf
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://research.tetonedge.net
  summary: functional data analysis using the square root slope framework
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: |
    A python package for functional data analysis using the square root 
    slope framework and curves using the square root velocity framework 
    which performs pair-wise and group-wise alignment as well as modeling 
    using functional component analysis and regression.
  doc_url: https://fdasrsf-python.readthedocs.io/
  dev_url: https://github.com/jdtuck/fdasrsf_python

extra:
  recipe-maintainers:
    - jdtuck
