{% set name = "fdasrsf" %}
{% set version = "2.5.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fdasrsf-{{ version }}.tar.gz
  sha256: 06e8fed94373a5264e65ab17dcc491db631c396f2e9c3744d9e370f31fc899ef

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                               # [build_platform != target_platform]
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
    - numpy {{ numpy }}                    # [build_platform != target_platform]
    - cython                               # [build_platform != target_platform]
    - cffi >=1.0.0                         # [build_platform != target_platform]
    - findblas                             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - blas-devel
  host:
    - python
    - setuptools
    - numpy {{ numpy }}
    - cffi >=1.0.0
    - findblas
    - cython >=0.29.17
    - pip
    - blas-devel
  run:
    - python
    - setuptools
    - numpy {{ numpy }}
    - cffi >=1.0.0
    - cython >=0.29.17
    - joblib >=0.16.0
    - matplotlib-base
    - numba >=0.51.2
    - patsy
    - pyparsing
    - scipy
    - six
    - tqdm

test:
  imports:
    - fdasrsf
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://research.tetonedge.net
  summary: functional data analysis using the square root slope framework
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: |
    A python package for functional data analysis using the square root 
    slope framework and curves using the square root velocity framework 
    which performs pair-wise and group-wise alignment as well as modeling 
    using functional component analysis and regression.
  doc_url: https://fdasrsf-python.readthedocs.io/
  dev_url: https://github.com/jdtuck/fdasrsf_python

extra:
  recipe-maintainers:
    - jdtuck
